---
- name: "AWS - Install docker"
  hosts: all
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - docker
        - git
        - mc
        - postgresql13-client

    - name: clean yum metadata cache
      command: yum clean metadata
      args:
        warn: false

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Enable Docker CE service at startup
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
      become: yes