version: '3.5'

services:
  postgresql:
    container_name: postgres-13.1-{{ role_name }}
    image: postgres:13.1
    restart: unless-stopped
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - ./postgres/conf:/etc/postgresql
      - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./postgres/scripts:/scripts

    env_file:
      - ./postgres/postgres.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

