---
- name: "Jenkins Install"
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: '{{ playbook_dir }}'
        name: jenkins_docker
        source: build

    - name: Ensure jenkins directory on docker host
      file:
        state: directory
        owner: 1000
        group: 1000
        path: /data/jenkins_home
      become: yes

    - name: Create a symbolic link
      ansible.builtin.file:
        src: /data/jenkins_home
        dest: /var/jenkins_home
        state: link
      become: yes

    - name: Create a container from the jenkins docker image
      docker_container:
        name: "jenkins-server"
        image: "jenkins_docker"
        restart_policy: "always"
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /data/jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
        state: started
        recreate: no
